package com.example.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;AddPatient_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.plugins.model.impl.PatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.plugins.model.impl.PatientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Patient
 * @see com.example.plugins.model.impl.PatientImpl
 * @see com.example.plugins.model.impl.PatientModelImpl
 * @generated
 */
public interface PatientModel extends BaseModel<Patient> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
     */

    /**
     * Returns the primary key of this patient.
     *
     * @return the primary key of this patient
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this patient.
     *
     * @param primaryKey the primary key of this patient
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the patient ID of this patient.
     *
     * @return the patient ID of this patient
     */
    public long getPatientId();

    /**
     * Sets the patient ID of this patient.
     *
     * @param patientId the patient ID of this patient
     */
    public void setPatientId(long patientId);

    /**
     * Returns the nom of this patient.
     *
     * @return the nom of this patient
     */
    @AutoEscape
    public String getNom();

    /**
     * Sets the nom of this patient.
     *
     * @param nom the nom of this patient
     */
    public void setNom(String nom);

    /**
     * Returns the prenom of this patient.
     *
     * @return the prenom of this patient
     */
    @AutoEscape
    public String getPrenom();

    /**
     * Sets the prenom of this patient.
     *
     * @param prenom the prenom of this patient
     */
    public void setPrenom(String prenom);

    /**
     * Returns the patient age of this patient.
     *
     * @return the patient age of this patient
     */
    public int getPatientAge();

    /**
     * Sets the patient age of this patient.
     *
     * @param patientAge the patient age of this patient
     */
    public void setPatientAge(int patientAge);

    /**
     * Returns the patient genre of this patient.
     *
     * @return the patient genre of this patient
     */
    public int getPatientGenre();

    /**
     * Sets the patient genre of this patient.
     *
     * @param patientGenre the patient genre of this patient
     */
    public void setPatientGenre(int patientGenre);

    /**
     * Returns the patient addresse of this patient.
     *
     * @return the patient addresse of this patient
     */
    @AutoEscape
    public String getPatientAddresse();

    /**
     * Sets the patient addresse of this patient.
     *
     * @param patientAddresse the patient addresse of this patient
     */
    public void setPatientAddresse(String patientAddresse);

    /**
     * Returns the patient email of this patient.
     *
     * @return the patient email of this patient
     */
    @AutoEscape
    public String getPatientEmail();

    /**
     * Sets the patient email of this patient.
     *
     * @param patientEmail the patient email of this patient
     */
    public void setPatientEmail(String patientEmail);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.plugins.model.Patient patient);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.plugins.model.Patient> toCacheModel();

    @Override
    public com.example.plugins.model.Patient toEscapedModel();

    @Override
    public com.example.plugins.model.Patient toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
